### ISSUE TITLE
MIP visualization

### ISSUE THREAD

**Issue by GiovanniSena** [GiovanniSena/LSFM#3] opened 2017-04-18 22:36 UTC
Between scans, we need to see the MIP of the previous time-point. At the moment, something is wrong with the range of pixel values used to render the image, and we always see it black...

**Comment by PaoloGB** [comment] 2017-05-15 21:59
As far as I remember this used to be the case: after each stack, the code would estimate the MIP and show that in the preview window. In the meantime it would calculate the transformation matrix.
I have no way to check what happened but I did notice that there is a new file called 
GUI_displayMIP_GS.m
in the GUI folder which is identical to the original one
GUI_displayMIP.m
but is lacking the normalization part.
The problem is that the two files have different names but the functions inside have the same
GUI_displayMIP
which means that one will override the other.

If the _GMS version is an attempt to fix the issue, than you should rename the old file to something different, including the function within.
However, I suspect the _GS version is the one that was creating the issue, so it should now be fine because I have renamed the function in the _GS file to be consistent with the file name.

**Comment by GiovanniSena** [comment] 2017-05-16 09:17
Thank you Paolo,
that might have been my fault, then.
I think Todd fixed the problem now. I will have him double-check that the GitHub version reflects his latest fixes, and post here the results.

**Comment by GiovanniSena** [comment] 2017-05-16 09:19
Todd, can you please read the above and make sure the file on GitHub reflect your latest fix on this issue? Thanks

**Comment by PaoloGB** [comment] 2017-05-16 09:25
No worries.
Please be aware that I have already committed a few changes to the repository and cleaned up the GUI, FilterWheel, CFG, Camera and FileIO folders.
So if you want to modify something use the commit process:

-checkout the current folder
-branch it
-modify the files
-commit the changes and push them to the repository
-create a merge request

This way we all work on the same files and we can avoid conflicts.

**Comment by GiovanniSena** [comment] 2017-05-16 10:22
So, just to be clear, you can "push" yourself the commits because you are a Collaborator? Another viewer could branch/modify/commit but will have to request a "pull" before his/her changes are merged in the Master?

**Comment by PaoloGB** [comment] 2017-05-19 00:18
I will close this issue as I think it is now solved (let me know if not clear).

**Closed as completed by PaoloGB** 2017-05-19 00:18 UTC
